LICENSE.txt
pom.xml

Fixing JENKINS-61240 and remove SCM tag for release

---

.gitignore
src/main/java/io/jenkins/plugins/veracode/api/ACWebRequestHandler.java
src/main/java/io/jenkins/plugins/veracode/utils/SystemUtil.java
src/main/java/io/jenkins/plugins/veracode/utils/UserAgentUtil.java

In this commit:
- Set ACWebRequestHandler to be used in the wrapper
- Correct the plugin name
- Update gitignore

Add init of web request handler and plugin name

---

Jenkinsfile
pom.xml
src/test/java/com/veracode/jenkins/plugin/utils/FileUtilTest.java
src/test/java/com/veracode/jenkins/plugin/utils/XmlUtilTest.java

- Added FindBugs
- Added Checkstyle 
- Added JaCoCo
- Added a couple of test-cases to show the trend change
- A sample report can be seen [here..](https://ci.jenkins.io/job/Plugins/job/veracode-scan-plugin/job/JENKINS-62232/)

JENKINS-62232 Implement Code Coverage in Open-source Jenkins Plugin

---

pom.xml
src/main/java/com/veracode/jenkins/plugin/VeracodeNotifier.java

Fixing automation test error caused by id/key fix.

fixing id/key issues.

---

.github/workflows/veracode-scan-master.yml
.github/workflows/veracode-scan.yml

1. Adding Master branch scan job in workflow to scan in policy level
2. Adding scheduler to scan weekly
3. Change old workflow job on non-master branch only.

Fix JENKINS-63065: adding master branch scan on policy scan weekly

---

src/main/java/com/veracode/jenkins/plugin/utils/XmlUtil.java
src/test/java/com/veracode/jenkins/plugin/utils/XmlUtilTest.java

Fix for Jenkins - Executive Summary links to wrong scan
Changes include
- Case insensitive search for sandbox name
- Unit tests

Fix for JENKINS-63641

---

Jenkinsfile
README.md

remove findbugs plugin due to Jenkins remove findbugs support last week.

merge dev to master

---

src/main/java/com/veracode/jenkins/plugin/DynamicAnalysisStartNotifier.java
src/main/java/com/veracode/jenkins/plugin/VeracodeNotifier.java

Modify Jenkins Plugin to no longer encrypt non-sensitive values in a job's config.xml file

JENKINS-64668 Not encrypt non-sensitive values

---

pom.xml
src/main/java/com/veracode/jenkins/plugin/VeracodePipelineRecorder.java
src/test/java/com/veracode/jenkins/plugin/VeracodePipelineRecorderTest.java

JENKINS-65680 Upload and Scan with Veracode Pipeline Jenkins Step Not Failing Pipeline

JENKINS-65680 Upload and Scan with Veracode Pipeline Jenkins Step Not Failing Pipeline

---

src/main/java/com/veracode/jenkins/plugin/VeracodePipelineRecorder.java
src/main/java/com/veracode/jenkins/plugin/args/UploadAndScanArgs.java
src/test/java/com/veracode/jenkins/plugin/VeracodePipelineRecorderTest.java
src/test/java/com/veracode/jenkins/plugin/args/UploadAndScanArgsTest.java

JENKINS-65499 Support debug flag for uploadandscan

---

.github/workflows/veracode-scan-master.yml
.github/workflows/veracode-scan.yml

JENKINS-65953 Add SCA Agent-Based scan into build pipeline

---

pom.xml
src/main/java/com/veracode/jenkins/plugin/DynamicAnalysisResultsAction.java
src/main/java/com/veracode/jenkins/plugin/VeracodeAction.java

JENKINS-66008 Fixing SCA Agent-Based scan issues

---

pom.xml

JENKINS-66143 Exclude log4j from jenkins-core and bump commons-compress version to 1.21

---

src/main/resources/com/veracode/jenkins/plugin/VeracodeNotifier/global.jelly
src/main/resources/com/veracode/jenkins/plugin/VeracodeNotifier/help-copyremotefiles.html
src/main/resources/com/veracode/jenkins/plugin/VeracodeNotifier/help-replacementpattern.html
src/main/resources/com/veracode/jenkins/plugin/VeracodePipelineRecorder/config.jelly
src/main/resources/com/veracode/jenkins/plugin/VeracodePipelineRecorder/help-copyRemoteFiles.html
src/main/resources/com/veracode/jenkins/plugin/VeracodePipelineRecorder/help-replacementPattern.html

JENKINS-66222 Update UI to replace the term master with Controller

---

pom.xml

JENKINS-66227 Upgrade Apache Ant Core version from 1.10.9 to 1.10.11

---

pom.xml

Update Plugin with Java Wrapper that supports the FedRAMP Region

---

src/main/java/com/veracode/jenkins/plugin/VeracodePipelineRecorder.java
src/test/java/com/veracode/jenkins/plugin/VeracodePipelineRecorderTest.java

JENKINS-66358 Missing uploadIncludePattern causes job to fail

---

src/main/java/com/veracode/jenkins/plugin/VeracodeNotifier.java
src/main/java/com/veracode/jenkins/plugin/VeracodePipelineRecorder.java
src/test/java/com/veracode/jenkins/plugin/VeracodeNotifierTest.java
src/test/java/com/veracode/jenkins/plugin/VeracodePipelineRecorderTest.java

JENKINS-66440 Fix for issue with remote node upload when using scan include parameter pulls wrong files

Fix for JENKINS-66440

---

pom.xml

Adding sonarqube task into pom file

Fixing JENKINS-66462, add sonarqube to pom file

---

pom.xml

JENKINS-67267 Update vosp-api-wrappers-java library version to v21.11.9.0

Update vosp-api-wrappers-java to v21.11.9.0

---

pom.xml

Update vosp-api-wrappers-java to v21.12.9.1

---

src/test/java/com/veracode/jenkins/plugin/testutils/XmlDocumentGenerator.java
src/test/java/com/veracode/jenkins/plugin/utils/EncryptionUtilTest.java
src/test/java/com/veracode/jenkins/plugin/utils/FileUtilTest.java
src/test/java/com/veracode/jenkins/plugin/utils/FormValidationUtilTest.java
src/test/java/com/veracode/jenkins/plugin/utils/RemoteScanUtilTest.java
src/test/java/com/veracode/jenkins/plugin/utils/StringUtilTest.java
src/test/java/com/veracode/jenkins/plugin/utils/UserAgentUtilTest.java
src/test/java/com/veracode/jenkins/plugin/utils/WrapperUtilTest.java
src/test/java/com/veracode/jenkins/plugin/utils/XmlUtilTest.java

Add unit tests for com.veracode.jenkins.plugin.utils package classes

---

pom.xml

Update vosp-api-wrappers-java library version to v22.1.9.3

Update vosp-api-wrappers-java library version to v22.1.9.3

---

.gitlab-ci.yml
pom.xml
src/test/java/com/veracode/jenkins/plugin/testutils/XmlDocumentGenerator.java
src/test/java/com/veracode/jenkins/plugin/utils/EncryptionUtilTest.java
src/test/java/com/veracode/jenkins/plugin/utils/FileUtilTest.java
src/test/java/com/veracode/jenkins/plugin/utils/FormValidationUtilTest.java
src/test/java/com/veracode/jenkins/plugin/utils/RemoteScanUtilTest.java
src/test/java/com/veracode/jenkins/plugin/utils/StringUtilTest.java
src/test/java/com/veracode/jenkins/plugin/utils/UserAgentUtilTest.java
src/test/java/com/veracode/jenkins/plugin/utils/WrapperUtilTest.java
src/test/java/com/veracode/jenkins/plugin/utils/XmlUtilTest.java

Per @sbuhary 's request: https://github.com/jenkinsci/veracode-scan-plugin/pull/68#issuecomment-1090353624
Dependabot made its branch from `master` and it looks like `dev` is quite a few commits behind. If you just want https://github.com/jenkinsci/veracode-scan-plugin/pull/68/commits/b2464a23dccae4501b693393ac5f095e6877efda on its own going into `dev`, let me know.

Dependabot/maven/org.springframework spring webmvc 5.3.18

---

src/main/java/com/veracode/jenkins/plugin/VeracodePipelineRecorder.java
src/main/java/com/veracode/jenkins/plugin/args/UploadAndScanArgs.java
src/main/resources/com/veracode/jenkins/plugin/VeracodePipelineRecorder/config.jelly
src/main/resources/com/veracode/jenkins/plugin/VeracodePipelineRecorder/help-deleteIncompleteScan.html
src/test/java/com/veracode/jenkins/plugin/VeracodePipelineRecorderTest.java
src/test/java/com/veracode/jenkins/plugin/args/UploadAndScanArgsTest.java

Add option to delete scans that have not been completed to the Jenkins plugin for Pipeline

---

src/main/java/com/veracode/jenkins/plugin/VeracodePipelineRecorder.java
src/main/java/com/veracode/jenkins/plugin/args/UploadAndScanArgs.java
src/test/java/com/veracode/jenkins/plugin/args/UploadAndScanArgsTest.java

Fix Exceptions while not passing deleteIncompleteScan and passing boolean values for deleteIncompleteScan

Fix JENKINS-68844

---

src/main/java/com/veracode/jenkins/plugin/DynamicAnalysisResultsAction.java
src/main/java/com/veracode/jenkins/plugin/DynamicAnalysisResultsNotifier.java
src/main/java/com/veracode/jenkins/plugin/DynamicAnalysisStartNotifier.java
src/main/java/com/veracode/jenkins/plugin/DynamicRescanNotifier.java
src/main/java/com/veracode/jenkins/plugin/VeracodeAction.java
src/main/java/com/veracode/jenkins/plugin/args/AbstractArgs.java
src/main/java/com/veracode/jenkins/plugin/args/DynamicRescanArgs.java
src/main/java/com/veracode/jenkins/plugin/args/UploadAndScanArgs.java
src/main/java/com/veracode/jenkins/plugin/data/SCAScanHistory.java
src/main/java/com/veracode/jenkins/plugin/data/ScanHistory.java
src/main/java/com/veracode/jenkins/plugin/utils/FileUtil.java
src/main/java/com/veracode/jenkins/plugin/utils/UserAgentUtil.java
src/main/java/com/veracode/jenkins/plugin/utils/XmlUtil.java
src/test/java/com/veracode/jenkins/plugin/utils/FileUtilTest.java
src/test/java/com/veracode/jenkins/plugin/utils/UserAgentUtilTest.java

Minor refactoring this time on branch `dev` as an alternative to #81:
* use `Jenkins.get()` instead of deprecated method
* use diamond operator
* manual min/max calculations
* merged identical catch branches

Minor Refactoring to dev branch

---

README.md
pom.xml
src/main/java/com/veracode/jenkins/plugin/common/DAAdapterService.java
src/main/resources/com/veracode/jenkins/plugin/DynamicAnalysisResultsNotifier/help-vid.html
src/main/resources/com/veracode/jenkins/plugin/DynamicAnalysisResultsNotifier/help-vkey.html
src/main/resources/com/veracode/jenkins/plugin/DynamicAnalysisStartNotifier/help-vid.html
src/main/resources/com/veracode/jenkins/plugin/DynamicAnalysisStartNotifier/help-vkey.html
src/main/resources/com/veracode/jenkins/plugin/DynamicRescanPipelineRecorder/help-vid.html
src/main/resources/com/veracode/jenkins/plugin/DynamicRescanPipelineRecorder/help-vkey.html
src/main/resources/com/veracode/jenkins/plugin/VeracodeNotifier/help-vid.html
src/main/resources/com/veracode/jenkins/plugin/VeracodeNotifier/help-vkey.html
src/main/resources/com/veracode/jenkins/plugin/VeracodePipelineRecorder/help-vid.html
src/main/resources/com/veracode/jenkins/plugin/VeracodePipelineRecorder/help-vkey.html
src/main/resources/index.jelly

Help Center to Documentation renaming, new DA statuses, latest API Wrapper containing new DA statuses and scan poll interval fix

Help Center to Documentation renaming, new DA statuses, latest API Wrapper

---

pom.xml
src/main/java/com/veracode/jenkins/plugin/VeracodeNotifier.java
src/main/java/com/veracode/jenkins/plugin/VeracodePipelineRecorder.java
src/main/resources/com/veracode/jenkins/plugin/VeracodeNotifier/global.jelly
src/main/resources/com/veracode/jenkins/plugin/VeracodeNotifier/help-failbuild.html
src/main/resources/com/veracode/jenkins/plugin/VeracodeNotifier/help-unstablebuild.html
src/main/resources/com/veracode/jenkins/plugin/VeracodePipelineRecorder/config.jelly
src/main/resources/com/veracode/jenkins/plugin/VeracodePipelineRecorder/help-canFailJob.html
src/main/resources/com/veracode/jenkins/plugin/VeracodePipelineRecorder/help-unstableBuild.html
src/test/java/com/veracode/jenkins/plugin/VeracodePipelineRecorderTest.java

Changes for release v23.5.21.0

---

pom.xml
src/main/java/com/veracode/jenkins/plugin/VeracodeNotifier.java
src/main/java/com/veracode/jenkins/plugin/VeracodePipelineRecorder.java
src/main/resources/com/veracode/jenkins/plugin/VeracodeNotifier/global.jelly
src/main/resources/com/veracode/jenkins/plugin/VeracodeNotifier/help-failbuild.html
src/main/resources/com/veracode/jenkins/plugin/VeracodePipelineRecorder/config.jelly
src/main/resources/com/veracode/jenkins/plugin/VeracodePipelineRecorder/help-canFailJob.html

Changes for release v23.7.22.0

---

.github/workflows/veracode-scan-master.yml
.github/workflows/veracode-scan.yml
Jenkinsfile
pom.xml
src/main/java/com/veracode/jenkins/plugin/DynamicAnalysisResultsAction.java
src/main/java/com/veracode/jenkins/plugin/VeracodeAction.java
src/test/java/com/veracode/jenkins/plugin/VeracodeNotifierTest.java
src/test/java/com/veracode/jenkins/plugin/VeracodePipelineRecorderTest.java
src/test/java/com/veracode/jenkins/plugin/args/UploadAndScanArgsTest.java
src/test/java/com/veracode/jenkins/plugin/utils/FileUtilTest.java
src/test/java/com/veracode/jenkins/plugin/utils/FormValidationUtilTest.java
src/test/java/com/veracode/jenkins/plugin/utils/WrapperUtilTest.java

Changes for release 24.2.23.0

---

pom.xml

Fixing JENKINS-75758, address some SCA issues.

Fixing JENKINS-75758
